### ISSUE TITLE
Problems stopping the server if music has been played

### ISSUE THREAD

**Issue by nvonbulow** [trenskow/libairfloat#5]
I have tested this implementation of the AirPlay Server. It works great! But one problem that I've been having is that if music has been streamed through the server within the past few seconds, maybe more or currently is streaming, the server will not stop, and the current thread will hang. Using the tools I have available, I have determined that it hangs due to a locked mutex. I generated a stack trace while it was hanging, and here it is:

```
    Thread 0 name:  Dispatch queue: com.apple.main-thread
    Thread 0:
    0       libsystem_pthread.dylib         0x19724573c 0x197244000 + 0x173c    // pthread_mutex_unlock + 0x18
    1     + libairfloat.dylib               0x1021de2cc 0x10213c000 + 0xa22cc   // web_server_connection_close + 0x54
    2     + libairfloat.dylib               0x1021de2cc 0x10213c000 + 0xa22cc   // web_server_connection_close + 0x54
    3     + libairfloat.dylib               0x1021d9b80 0x10213c000 + 0x9db80   // raop_session_stop + 0x24
    4     + libairfloat.dylib               0x1021d9d34 0x10213c000 + 0x9dd34   // raop_session_destroy + 0x2c
    5     + libairfloat.dylib               0x1021d869c 0x10213c000 + 0x9c69c   // raop_server_stop + 0x38
    6     + libairfloat.dylib               0x1021d03f4 0x10213c000 + 0x943f4   // -[AirPlayServer stop] + 0x20
```

And looking at the disassembly, I can determine that the problem is the first `mutex_lock` in the `web_server_connection_close` function. I don't know where this mutex is being locked and then not being unlocked though.

```
void web_server_connection_close(struct web_server_connection_t* wc) {

        mutex_lock(wc->mutex); //This mutex seems to already be locked

    if (wc->is_connected) {

        log_message(LOG_INFO, "Client disconnected");

        wc->is_connected = false;

        socket_close(wc->socket);

        mutex_unlock(wc->mutex);

        if (wc->closed_callback != NULL)
            wc->closed_callback(wc, wc->closed_callback_ctx);

        mutex_lock(wc->mutex);

    }

    mutex_unlock(wc->mutex);

}
```

One of the requirements for my app is that you be able to stop the server while it is streaming.

Great job on what works though!

**Comment by trenskow** [comment]
Hi @101timjim 

There is some mess in the tear down of servers and connections. There are some issues with memory being freed before other objects was done using it - basic race condition. The solution back then was the ease one where I threw some locks in there.

I think the only solution is to do some thorough breakdown of the connection close / shut down to determine a proper tear down sequence.

On a sidenote I've been thinking about restructuring it in C++ using smart pointers to better handle the memory issues.
